import os

FEATURE_FLAGS = {
    "ENABLE_TEMPLATE_PROCESSING": True,
}

ENABLE_PROXY_FIX = True

SECRET_KEY = os.environ.get("SECRET_KEY")

SQLALCHEMY_DATABASE_URI = os.environ.get("DATABASE")

###AUTH_ROLE_PUBLIC = 'Public'
###PUBLIC_ROLE_LIKE = 'Gamma'
###PUBLIC_ROLE_LIKE_GAMMA = True
